import { Controller } from "@hotwired/stimulus"


export default class extends Controller {
  static targets = [ "rowHeader", "tbody", "menu","buyLocation", "buyCommodity", "commoditiesData", "sellLocation", "menuItem", "newTradeSession", "mainMenu","existingTradeSession" ]
  activeIndex = 0;

  
  rowCount = 5; // change this to the number of rows in your table


  connect() {
    //this.addRows();
    window.addEventListener('resize', this.addRows.bind(this));
    
    this.activeIndex = 0;
    this.setActiveItem();
    document.addEventListener("keydown", this.handleKeydown.bind(this));

    document.querySelectorAll('#traderun-menu').forEach((menu) => {
      const menuItems = menu.querySelectorAll('a');
      menuItems[this.activeIndex].classList.add('active');

      document.addEventListener('keydown', (event) => {
        const key = event.key;
        let nextIndex = this.activeIndex;
        if (key === 'ArrowLeft' || key === 'ArrowUp') {
          console.log('left');
          nextIndex = (this.activeIndex === 0) ? menuItems.length - 1 : this.activeIndex - 1;
        } else if (key === 'ArrowRight' || key === 'ArrowDown') {
          console.log('right');
          nextIndex = (this.activeIndex === menuItems.length - 1) ? 0 : this.activeIndex + 1;
        }
        if (key === " ") {          
          event.preventDefault();
        }
        if (nextIndex !== this.activeIndex) {
          menuItems[this.activeIndex].classList.remove('active');
          this.activeIndex = nextIndex;
          menuItems[this.activeIndex].classList.add('active');
        }
      });
    });



    this.updateTraderunFooterVisibility();
    this.observeDOMChanges();


    document.addEventListener("keydown", function(event) {
      // Check if the key pressed was the "enter" key
      
      if (event.key === '/') {
        document.querySelector('#traderun-menu').classList.toggle('hidden');
      }
    });
  }


  // Function added to hide the greeting

  disconnect() {
    if (this.observer) {
      this.observer.disconnect();
    }
  }

  updateTraderunFooterVisibility() {
    var greetingElement = document.querySelector('#greeting');
    var traderunFooterElement = document.querySelector('#traderun_footer');
    var isGreetingHidden = greetingElement && greetingElement.classList.contains('hidden');

    if (!isGreetingHidden && traderunFooterElement) {
      traderunFooterElement.style.display = 'none';
    } else if (traderunFooterElement) {
      traderunFooterElement.style.display = '';
    }
  }

  observeDOMChanges() {
    this.observer = new MutationObserver((mutations) => {
      this.updateTraderunFooterVisibility();
    });

    var config = {
      attributes: true,
      childList: true,
      subtree: true,
      attributeFilter: ['class']
    };

    this.observer.observe(document.body, config);
  }

  // end of greeting function


  handleKeydown(event) {
    if (event.key === "ArrowUp") {
      this.activeIndex = Math.max(0, this.activeIndex - 1);
    } else if (event.key === "ArrowDown") {
      this.activeIndex = Math.min(this.menuItemTargets.length - 1, this.activeIndex + 1);
    } else if (event.key === "Escape") {
      if (document.querySelector("#traderun_footer")) {        
        // Trigger the Rails action associated with the traderun_command_path("back")
        window.location.href = "/traderun_command.back";
        // Replace "/traderun_command/back" with the actual path generated by traderun_command_path("back") if it's different
      }
    }else if (event.key === "Enter") {
      if (this.menuItemTargets[this.activeIndex].dataset.action === "startNewTradeRun") {
        this.mainMenuTargets.forEach(menu => menu.classList.add("hidden"));
        document.querySelector('#greeting').classList.add('hidden');              
        this.newTradeSessionTarget.classList.remove("hidden");
        this.fillBackground();
        const inputField = document.querySelector('#trade_session_session_date');
        if (inputField) {                 
          setTimeout(() => {
            inputField.focus();
          }, 1000); 
        }
      }else if (this.menuItemTargets[this.activeIndex].dataset.action === "existingTradeSession") {
        this.mainMenuTargets.forEach(menu => menu.classList.add("hidden"));
        document.querySelector('#greeting').classList.add('hidden');              
        this.existingTradeSessionTarget.classList.remove("hidden");
        this.fillBackground();
        
      }else{
        const activeMenuItem = this.menuItemTargets[this.activeIndex];
        const activeLink = activeMenuItem.querySelector('a');
    
        if (activeLink) {
          window.location.href = activeLink.href;
        }
      }
    }
    this.setActiveItem();
  }

  fillBackground() {
    const charBackground = document.querySelector('#charContent');
    const character = '░';

    const fontSize = 16; // Adjust this value to your desired font size
    const lineHeight = 1.0; // Adjust this value to match your desired line height
  
    charBackground.style.fontSize = `${fontSize}px`;
    charBackground.style.lineHeight = lineHeight;
  
    const width = window.innerWidth;
    const height = window.innerHeight;
  
    const columns = Math.ceil((width*2) / fontSize);
    const rows = Math.ceil(height / (fontSize * lineHeight));
  
    let backgroundString = '';
  
    for (let i = 0; i < rows; i++) {
      for (let j = 0; j < columns; j++) {
        backgroundString += character;
      }
      backgroundString += '\n';
    }
  
    charBackground.textContent = backgroundString;
  
  }


  setActiveItem() {
    this.menuItemTargets.forEach((item, index) => {
      item.classList.toggle("active", index === this.activeIndex);
    });
  }

   
  shipSelect(){
    let shipsDataElement = document.getElementById("ships-data");
    let shipsData = JSON.parse(shipsDataElement.dataset.ships);
    let buySCUElement = document.getElementById("buySCU");
    let sellSCUElement = document.getElementById("sellSCU");
    let scusHtml = "";
    
    let selectedShipName = event.target.value;
    if (selectedShipName) {
      let selectedShip = shipsData.find(ship => ship.model === selectedShipName)
      if (selectedShip) {        
        buySCUElement.innerHTML = `${selectedShip.scu}`
        sellSCUElement.innerHTML = `${selectedShip.scu}`
      } else {
        buySCUElement.innerHTML = '<p>No ship found.</p>'
      }
    } else {
      buySCUElement.innerHTML = ''
      sellSCUElement.innerHTML = ''
    }
   this.calculator(event);
  }

  buyLocation(){
    this.populateCommoditySelect();
    this.calculator(event);
  }

  buyCommodity(){
    const commoditiesDataElement = document.getElementById("commodities-data");
    const username = document.getElementById("trade_run_username").value;
    const locationData = document.getElementById("trade_run_buy_location").value;
    const ship = document.getElementById("trade_run_ship").value;    
    const commoditiesData = JSON.parse(commoditiesDataElement.dataset.commodities);
    const buyPriceElement = document.getElementById("buyPrice");
    const deltaElement = document.getElementById("delta");

    
    const selectedCommodityName = event.target.value    
    let activeCommodity = []
    if (locationData) {
       activeCommodity = commoditiesData.find(commodity => commodity.name === selectedCommodityName   && commodity.location === locationData)
      if (activeCommodity) {        
        buyPriceElement.innerHTML = `${activeCommodity.sell}`
        deltaElement.setAttribute("marketSell", activeCommodity.sell);
      } else {
        buyPriceElement.innerHTML = 'null'
        deltaElement.setAttribute("marketSell", '0');
      }
    } else {
      buyPriceElement.innerHTML = ''
      
    }
    this.calculator(event);
    this.populateSellLocationSelect(); 
    if(locationData && activeCommodity && username && ship){
    //document.getElementById("traderuns_form").submit();
    }

  }

  sellLocation(){
    const commoditiesDataElement = document.getElementById("commodities-data");
    const commoditiesData = JSON.parse(commoditiesDataElement.dataset.commodities);
    const buyPriceElement = document.getElementById("sellPrice");
    const locationData = document.getElementById("trade_run_sell_location").value;
    const selectedCommodityName = document.getElementById("trade_run_buy_commodity").value;
    // const selectedCommodityName = event.target.value    
    console.log('sellLocation');
    const deltaElement = document.getElementById("delta");
    if (locationData) {
      const activeCommodity = commoditiesData.find(commodity => commodity.name === selectedCommodityName   && commodity.location === locationData)
      if (activeCommodity) {        
        buyPriceElement.innerHTML = `${activeCommodity.buy}`
        deltaElement.setAttribute("marketBuy", activeCommodity.buy);
      } else {
        buyPriceElement.innerHTML = 'null'
      }
    } else {
      buyPriceElement.innerHTML = ''
      
    }
    this.calculator(event);
  }

  createRun() {    
    const username = document.getElementById("trade_run_username").value;
    const locationData = document.getElementById("trade_run_buy_location").value;
    const ship = document.getElementById("trade_run_ship").value;
    const activeCommodity = document.getElementById("trade_run_buy_commodity").value;    
    event.target.innerHTML = "[X]";
    if(locationData && activeCommodity && username && ship){

      document.getElementById("scu_input").value = document.getElementById("sellSCU").innerHTML;
      document.getElementById("buy_price_input").value = document.getElementById("buyPrice").innerHTML;
      document.getElementById("delta_input").value = document.getElementById("delta").innerHTML;
      document.getElementById("sell_price_input").value = document.getElementById("sellPrice").innerHTML;


      document.getElementById("traderuns_form").submit();
      }else{
        let element = event.target;

        setTimeout(() => {
          element.innerHTML = "[  ]";
        }, 1000);
      }
  }
  
  addRows() {
    
    let tbody = this.tbodyTarget;
    let rowHeight = tbody.offsetHeight / this.rowCount;
    let windowHeight = window.innerHeight;
    let maxRowCount = Math.floor((windowHeight - tbody.offsetTop) / rowHeight);
    let html = '';

    for (let i = this.rowCount + 1; i <= maxRowCount; i++) {
      html += `<tr><td class="rownumber">${i}</td><td contenteditable="true"></td><td contenteditable="true"></td><td contenteditable="true"></td></tr>`;
    }

    tbody.insertAdjacentHTML('beforeend', html);
    this.rowCount = maxRowCount;
  }

  onContentChange(event){

    this.calculator(event);

  }

calculator(){
  
  let buyingPrice = parseFloat(document.getElementById("buyPrice").innerHTML)  * 100.00;
  //let sellPriceElement = parseFloat(document.getElementById("sellPrice").innerHTML)   * 100.00;
  let sellingPrice =  parseFloat(document.getElementById("sellPrice").innerHTML) * 100;
  // calculate sale price
  let sellLocation = this.sellLocationTarget.value;
  let buyLocation = this.buyLocationTarget.value;
  let selectedCommodity = this.buyCommodityTarget.value;
  let commoditiesData = JSON.parse(this.commoditiesDataTarget.dataset.commodities);
  let buyCommodity = commoditiesData.find(commodity => commodity.name === selectedCommodity && commodity.location === buyLocation);
  let sellCommodity = commoditiesData.find(commodity => commodity.name === selectedCommodity && commodity.location === sellLocation);  
  let buySCUElement = parseFloat(document.getElementById("buySCU").innerHTML);
  let capitalElement = document.getElementById("capital");
  let profitElement = document.getElementById("profit");
  let incomeElement = document.getElementById("income");
  let capitalCalculation = buyingPrice * buySCUElement;
  let deltaElement = document.getElementById("delta");
  
  let marketBuy = 0;
  let marketSell = 0;
 console.log('buyCommodity', buyCommodity);
 console.log('sellCommodity:', sellCommodity);
if (sellCommodity){
  marketSell = sellCommodity.buy;
}
if (buyCommodity){
 marketBuy = buyCommodity.sell;
}

deltaElement.setAttribute("marketSell", marketSell);
deltaElement.setAttribute("marketBuy", marketBuy);


if (event.target.id === 'buyPrice'){
  console.log('buyPrice');
  if (buyCommodity){
    buyingPrice =  parseFloat(document.getElementById("sellPrice").innerHTML) * 100;
   // sellingPrice = parseFloat(buyCommodity.buy)  * 100;
    //document.getElementById("sellPrice").innerHTML = buyCommodity.buy;
    // deltaElement.setAttribute("marketBuy", marketBuy);
   //  marketBuy = sellingPrice;    
  }else{
    document.getElementById("sellPrice").innerHTML = "ERR"
  }
}else if(event.target.id === 'sellPrice'){
  console.log('sellPrice');
  if (sellCommodity){
    sellingPrice =  parseFloat(document.getElementById("sellPrice").innerHTML) * 100;
   // document.getElementById("sellPrice").innerHTML = buyCommodity.buy;
  //  deltaElement.setAttribute("marketBuy", buyCommodity.sell);
  //   marketBuy = sellingPrice;    
  }else{
    document.getElementById("sellPrice").innerHTML = "ERR"
  }
}else{
  
  document.getElementById("sellPrice").innerHTML = marketSell;
  sellingPrice = parseFloat(marketSell)  * 100;
  console.log('other', marketSell);
}

if (event.target.id === 'sellPrice'){


//sellingPrice = parseFloat(document.getElementById("sellPrice").innerHTML) * 100;
//deltaElement.setAttribute("marketBuy", sellingPrice);

}

 // let marketSell = buyPriceElement;
//  let marketBuy = parseFloat(deltaElement.getAttribute("marketBuy")) * 100;
  let sellSCUElement = parseFloat(document.getElementById("sellSCU").innerHTML);

  let incomeCalculation = sellingPrice * sellSCUElement;
 
  let profitCalculation = (incomeCalculation - capitalCalculation);
  
  let deltaCalculation = profitCalculation - (((marketSell*100)  * buySCUElement) - ((marketBuy*100)  * sellSCUElement));



  if (deltaCalculation){    
    deltaElement.innerHTML = `${Math.round(deltaCalculation)}`;
  }

  if (capitalCalculation > 0){
    capitalElement.innerHTML = `${Math.round(capitalCalculation)}`;
  }

  if (incomeCalculation > 0){
    incomeElement.innerHTML = `${Math.round(incomeCalculation)}`;
  }

  if (profitCalculation > 0){
    profitElement.innerHTML = `${Math.round(profitCalculation)}`;
  }
}

  populateCommoditySelect() {
    const location = this.buyLocationTarget.value
    
    const commoditiesData = JSON.parse(this.commoditiesDataTarget.dataset.commodities)
    const commodities = commoditiesData.filter(commodity => commodity.location === location)

    this.buyCommodityTarget.innerHTML = ""
    commodities.forEach(commodity => {
      const option = document.createElement("option")
      option.value = commodity.name
      option.text = commodity.name
      this.buyCommodityTarget.add(option)
    })
  }

  populateSellLocationSelect() {
    const selectedCommodity = this.buyCommodityTarget.value
    const commoditiesData = JSON.parse(this.commoditiesDataTarget.dataset.commodities)
    const sellLocations = commoditiesData.filter(commodity => commodity.name === selectedCommodity && commodity.buy > 0)

    this.sellLocationTarget.innerHTML = ""
    // Add the "Please Select location" option as the first choice
    const defaultOption = document.createElement("option")
    defaultOption.value = ""
    defaultOption.text = "Sell location"
    this.sellLocationTarget.add(defaultOption)

    sellLocations.forEach(sellLocation => {
      const option = document.createElement("option")
      option.value = sellLocation.location
      option.text = sellLocation.location
      this.sellLocationTarget.add(option)
    })
  }



}