Manufacturers.create(id: '1', name: 'Origin Jumpworks (ORIG)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '2', name: 'Crusader Industries (CRUS)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '3', name: 'Anvil Aerospace (ANVL)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '4', name: 'Roberts Space Industries (RSI)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '5', name: 'Aegis Dynamics (AEGS)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '6', name: 'Esperia (ESPR)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '7', name: 'Drake Interplanetary (DRAK)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '8', name: 'Tumbril Land Systems (TMBL)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '9', name: 'Banu (BANU)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '10', name: 'Musashi Industrial & Starflight Concern (MISC)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '11', name: 'Consolidated Outland (CNOU)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '12', name: 'Aopoa (XIAN)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '13', name: 'Argo Astronautics (ARGO)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '14', name: 'Kruger Intergalatic (KRIG)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '15', name: 'Greycat Industrial (GRIN)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
Manufacturers.create(id: '16', name: 'Vanduul Components - Generic (VNCL)', description: '', origin_location: '', created_at: '', updated_at: '', logo: '')
