RsiUser.create(username: '7ylo', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'shyCanadien', title: 'Board Member', link: '')
RsiUser.create(username: 'YourDriver', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'getnghost', title: 'Executive', link: '')
RsiUser.create(username: 'Nevs', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Griffin Locksley', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'PerCapita', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Danither', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Sinnicle', title: 'Board Member', link: '')
RsiUser.create(username: 'Seggellion', title: 'Board Member', link: '')
RsiUser.create(username: 'CatalystDM', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Holstencoop', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Hermit-Mech', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'DogmaticOne', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Flywheelz', title: 'Member-Owner', link: '')
RsiUser.create(username: 'HOOVASTANK', title: 'Member-Owner', link: '')
RsiUser.create(username: 'sleighhjayy', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'TheRevTrev', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Daner', title: 'Member-Owner', link: '')
RsiUser.create(username: 'NaughtyPickle', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Poutinebbq', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'NebulaStorm', title: 'Member-Owner', link: '')
RsiUser.create(username: 'TheTobyOne', title: 'Member-Owner', link: '')
RsiUser.create(username: 'EarthBoundSpaceExplorer', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Rhys_Vizsla', title: 'Member-Owner', link: '')
RsiUser.create(username: 'TauntingPlace89', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Holt', title: 'Member-Owner', link: '')
RsiUser.create(username: 'MoMs', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Gavin-Bombay', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Mill Shive', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Zodd', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'E10E10', title: 'Flight Crew', link: '')
RsiUser.create(username: 'OPSCHIEF', title: 'Member-Owner', link: '')
RsiUser.create(username: 'J. Beatnik', title: 'Member-Owner', link: '')
RsiUser.create(username: 'MaidenAriana', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Phill75', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Stewart McCoy', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Valinar', title: 'Flight Crew', link: '')
RsiUser.create(username: 'Veranos', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'KrayzieZombie', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'MAX_THRUST', title: 'Flight Crew', link: '')
RsiUser.create(username: 'Heavy_Bob', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Implausible', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Jadjad', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Willie Corto', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Infiernos', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Citizen Ed', title: 'Partner', link: '')
RsiUser.create(username: 'SpectreEH', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Rednecketry', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'starlord', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Kane Vilorde', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'HomeroomLive.TTV', title: 'Member-Owner', link: '')
RsiUser.create(username: 'jMANSGHOST', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'GirlyGhost', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Verpine', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Captain-MikeDK', title: 'Executive', link: '')
RsiUser.create(username: 'Primus Caelius Placidus', title: 'Member-Owner', link: '')
RsiUser.create(username: 'eye_macher', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Cooter Holmes', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Shayps', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Negan', title: 'Flight Crew', link: '')
RsiUser.create(username: 'Al Wilder', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Afterburner', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Luap', title: 'Member-Owner', link: '')
RsiUser.create(username: 'OrionSpawn', title: 'Member-Owner', link: '')
RsiUser.create(username: 'LORD SHADOW', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Cor5air', title: 'Partner', link: '')
RsiUser.create(username: 'DutchFly-DRNL', title: 'Partner', link: '')
RsiUser.create(username: 'The Eradicator', title: 'Executive', link: '')
RsiUser.create(username: 'VashVendar', title: 'Member-Owner', link: '')
RsiUser.create(username: 'TheKoolAid', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Captain_BlueEyes', title: 'Partner', link: '')
RsiUser.create(username: 'Nemo', title: 'Member-Owner', link: '')
RsiUser.create(username: 'ReJoyce', title: 'Member-Owner', link: '')
RsiUser.create(username: 'UltraWee', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Ocypeta', title: 'Member-Owner', link: '')
RsiUser.create(username: 'montr0s', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Shorty01', title: 'Executive', link: '')
RsiUser.create(username: 'Jvtizzle', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Impyral', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Iron Dragoon', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Bartman', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Sredni Vashtar', title: 'Partner', link: '')
RsiUser.create(username: 'Delta Lima', title: 'Partner', link: '')
RsiUser.create(username: '[PHII] Flexxe', title: 'Partner', link: '')
RsiUser.create(username: 'Jack Axton', title: 'Partner', link: '')
RsiUser.create(username: 'edge300', title: 'Member-Owner', link: '')
RsiUser.create(username: 'VLAmander', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Y05H1', title: 'Member-Owner', link: '')
RsiUser.create(username: 'FloppyDonkey', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Balorn', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Jnoh', title: 'Member-Owner', link: '')
RsiUser.create(username: '-Firestar-', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Alpakka', title: 'Member-Owner', link: '')
RsiUser.create(username: 'InfinityOwl', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Egghead', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Ninjassic', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Nick Revokir', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Kinshadow, Master of Waffles', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Jerric &quot;Lord&quot; Kryos', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Webb', title: 'Member-Owner', link: '')
RsiUser.create(username: 'TGWS | Lychondy', title: 'Member-Owner', link: '')
RsiUser.create(username: 'FEEDMASTER', title: 'Member-Owner', link: '')
RsiUser.create(username: 'MrDelightful', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'SushiBagel', title: 'Member-Owner', link: '')
RsiUser.create(username: 'CrazyCanuck', title: 'Member-Owner', link: '')
RsiUser.create(username: 'Whenyoucant', title: 'Executive', link: '')
RsiUser.create(username: 'Mr.Zhypo', title: 'Flight Crew', link: '')
RsiUser.create(username: 'Cypher', title: 'Worker-Owner', link: '')
RsiUser.create(username: 'Eagles', title: 'Worker-Owner', link: '')
