RsiUser.create(name: 'TheRevTrev', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Daner', title: 'Member-Owner', link: '')
RsiUser.create(name: 'NaughtyPickle', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Poutinebbq', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'NebulaStorm', title: 'Member-Owner', link: '')
RsiUser.create(name: 'TheTobyOne', title: 'Member-Owner', link: '')
RsiUser.create(name: 'EarthBoundSpaceExplorer', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Rhys_Vizsla', title: 'Member-Owner', link: '')
RsiUser.create(name: 'TauntingPlace89', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Holt', title: 'Member-Owner', link: '')
RsiUser.create(name: 'MoMs', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Gavin-Bombay', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Mill Shive', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Zodd', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'E10E10', title: 'Flight Crew', link: '')
RsiUser.create(name: 'OPSCHIEF', title: 'Member-Owner', link: '')
RsiUser.create(name: 'J. Beatnik', title: 'Member-Owner', link: '')
RsiUser.create(name: 'MaidenAriana', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Phill75', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Stewart McCoy', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Valinar', title: 'Flight Crew', link: '')
RsiUser.create(name: 'Veranos', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'KrayzieZombie', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'MAX_THRUST', title: 'Flight Crew', link: '')
RsiUser.create(name: 'Heavy_Bob', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Implausible', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Jadjad', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Willie Corto', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Infiernos', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Citizen Ed', title: 'Partner', link: '')
RsiUser.create(name: 'SpectreEH', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Rednecketry', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'starlord', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Kane Vilorde', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'HomeroomLive.TTV', title: 'Member-Owner', link: '')
RsiUser.create(name: 'jMANSGHOST', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'GirlyGhost', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Verpine', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Captain-MikeDK', title: 'Executive', link: '')
RsiUser.create(name: 'Primus Caelius Placidus', title: 'Member-Owner', link: '')
RsiUser.create(name: 'eye_macher', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Cooter Holmes', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Shayps', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Negan', title: 'Flight Crew', link: '')
RsiUser.create(name: 'Al Wilder', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Afterburner', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Luap', title: 'Member-Owner', link: '')
RsiUser.create(name: 'OrionSpawn', title: 'Member-Owner', link: '')
RsiUser.create(name: 'LORD SHADOW', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Cor5air', title: 'Partner', link: '')
RsiUser.create(name: 'DutchFly-DRNL', title: 'Partner', link: '')
RsiUser.create(name: 'The Eradicator', title: 'Executive', link: '')
RsiUser.create(name: 'VashVendar', title: 'Member-Owner', link: '')
RsiUser.create(name: 'TheKoolAid', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Captain_BlueEyes', title: 'Partner', link: '')
RsiUser.create(name: 'Nemo', title: 'Member-Owner', link: '')
RsiUser.create(name: 'ReJoyce', title: 'Member-Owner', link: '')
RsiUser.create(name: 'UltraWee', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Ocypeta', title: 'Member-Owner', link: '')
RsiUser.create(name: 'montr0s', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Shorty01', title: 'Executive', link: '')
RsiUser.create(name: 'Jvtizzle', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Impyral', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Iron Dragoon', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Bartman', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Sredni Vashtar', title: 'Partner', link: '')
RsiUser.create(name: 'Delta Lima', title: 'Partner', link: '')
RsiUser.create(name: '[PHII] Flexxe', title: 'Partner', link: '')
RsiUser.create(name: 'Jack Axton', title: 'Partner', link: '')
RsiUser.create(name: 'edge300', title: 'Member-Owner', link: '')
RsiUser.create(name: 'VLAmander', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Y05H1', title: 'Member-Owner', link: '')
RsiUser.create(name: 'FloppyDonkey', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Balorn', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Jnoh', title: 'Member-Owner', link: '')
RsiUser.create(name: '-Firestar-', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Alpakka', title: 'Member-Owner', link: '')
RsiUser.create(name: 'InfinityOwl', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Egghead', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Ninjassic', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Nick Revokir', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Kinshadow, Master of Waffles', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Jerric &quot;Lord&quot; Kryos', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Webb', title: 'Member-Owner', link: '')
RsiUser.create(name: 'TGWS | Lychondy', title: 'Member-Owner', link: '')
RsiUser.create(name: 'FEEDMASTER', title: 'Member-Owner', link: '')
RsiUser.create(name: 'MrDelightful', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'SushiBagel', title: 'Member-Owner', link: '')
RsiUser.create(name: 'CrazyCanuck', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Whenyoucant', title: 'Executive', link: '')
RsiUser.create(name: 'Mr.Zhypo', title: 'Flight Crew', link: '')
RsiUser.create(name: 'Cypher', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Eagles', title: 'Worker-Owner', link: '')
RsiUser.create(name: '7ylo', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'shyCanadien', title: 'Board Member', link: '')
RsiUser.create(name: 'YourDriver', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'getnghost', title: 'Executive', link: '')
RsiUser.create(name: 'Nevs', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Griffin Locksley', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'PerCapita', title: 'Member-Owner', link: '')
RsiUser.create(name: 'Danither', title: 'Worker-Owner', link: '')
RsiUser.create(name: 'Sinnicle', title: 'Board Member', link: '')
RsiUser.create(name: 'Seggellion', title: 'Board Member', link: '')
